remote_theme : BlackrockDigital/startbootstrap-clean-blog-jekyll
title:              riri's Potpolio
email:              ehquf8011@gmail.com
description:        
author:             Start Bootstrap
baseurl:            ""
url:                "https://ririkat.github.io"

# Social Profiles
twitter_username:  
github_username:    ririkat
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
# kramdown
markdown:           typora
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
